spring:
  datasource:
    password: Salacca
    username: salak
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security_kit_browser?useUnicode=yes&characterEncoding=UTF-8&useSSL=false