@startuml

actor 资源所有者

== 获取令牌 ==
资源所有者 -> 第三方应用: 访问Client
第三方应用 -> 资源所有者: 返回授权路径将用户导向认证服务器
activate 第三方应用
activate 资源所有者
资源所有者 -> 服务提供商@认证服务器: 用户同意授权
deactivate 资源所有者
服务提供商@认证服务器 -> 第三方应用: 回调第三方应用返回授权码
第三方应用 -> 服务提供商@认证服务器: 申请令牌
deactivate 第三方应用
服务提供商@认证服务器 -> 第三方应用: 发放令牌

== 获取资源 ==
第三方应用 -> 服务提供商@资源服务器: 申请资源
服务提供商@资源服务器 -> 第三方应用: 返回资源

@enduml